// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DeleteImproveRequestService is an autogenerated mock type for the DeleteImproveRequestService type
type DeleteImproveRequestService struct {
	mock.Mock
}

type DeleteImproveRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteImproveRequestService) EXPECT() *DeleteImproveRequestService_Expecter {
	return &DeleteImproveRequestService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, tokenRaw, id
func (_m *DeleteImproveRequestService) Delete(ctx context.Context, tokenRaw string, id uuid.UUID) error {
	ret := _m.Called(ctx, tokenRaw, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, tokenRaw, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImproveRequestService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DeleteImproveRequestService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - id uuid.UUID
func (_e *DeleteImproveRequestService_Expecter) Delete(ctx interface{}, tokenRaw interface{}, id interface{}) *DeleteImproveRequestService_Delete_Call {
	return &DeleteImproveRequestService_Delete_Call{Call: _e.mock.On("Delete", ctx, tokenRaw, id)}
}

func (_c *DeleteImproveRequestService_Delete_Call) Run(run func(ctx context.Context, tokenRaw string, id uuid.UUID)) *DeleteImproveRequestService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DeleteImproveRequestService_Delete_Call) Return(_a0 error) *DeleteImproveRequestService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteImproveRequestService_Delete_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) error) *DeleteImproveRequestService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDeleteImproveRequestService interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteImproveRequestService creates a new instance of DeleteImproveRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteImproveRequestService(t mockConstructorTestingTNewDeleteImproveRequestService) *DeleteImproveRequestService {
	mock := &DeleteImproveRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
