// Code generated by mockery v2.33.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/forum-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ListImproveRequestsService is an autogenerated mock type for the ListImproveRequestsService type
type ListImproveRequestsService struct {
	mock.Mock
}

type ListImproveRequestsService_Expecter struct {
	mock *mock.Mock
}

func (_m *ListImproveRequestsService) EXPECT() *ListImproveRequestsService_Expecter {
	return &ListImproveRequestsService_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, ids
func (_m *ListImproveRequestsService) List(ctx context.Context, ids []uuid.UUID) ([]*models.ImproveRequestPreview, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.ImproveRequestPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*models.ImproveRequestPreview, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*models.ImproveRequestPreview); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImproveRequestPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListImproveRequestsService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ListImproveRequestsService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *ListImproveRequestsService_Expecter) List(ctx interface{}, ids interface{}) *ListImproveRequestsService_List_Call {
	return &ListImproveRequestsService_List_Call{Call: _e.mock.On("List", ctx, ids)}
}

func (_c *ListImproveRequestsService_List_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *ListImproveRequestsService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *ListImproveRequestsService_List_Call) Return(_a0 []*models.ImproveRequestPreview, _a1 error) *ListImproveRequestsService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListImproveRequestsService_List_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*models.ImproveRequestPreview, error)) *ListImproveRequestsService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewListImproveRequestsService creates a new instance of ListImproveRequestsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListImproveRequestsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListImproveRequestsService {
	mock := &ListImproveRequestsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
