// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/forum-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// SearchImproveRequestsService is an autogenerated mock type for the SearchImproveRequestsService type
type SearchImproveRequestsService struct {
	mock.Mock
}

type SearchImproveRequestsService_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchImproveRequestsService) EXPECT() *SearchImproveRequestsService_Expecter {
	return &SearchImproveRequestsService_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, query
func (_m *SearchImproveRequestsService) Search(ctx context.Context, query models.SearchImproveRequestsQuery) ([]*models.ImproveRequestPreview, int, error) {
	ret := _m.Called(ctx, query)

	var r0 []*models.ImproveRequestPreview
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SearchImproveRequestsQuery) ([]*models.ImproveRequestPreview, int, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SearchImproveRequestsQuery) []*models.ImproveRequestPreview); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ImproveRequestPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SearchImproveRequestsQuery) int); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.SearchImproveRequestsQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SearchImproveRequestsService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type SearchImproveRequestsService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query models.SearchImproveRequestsQuery
func (_e *SearchImproveRequestsService_Expecter) Search(ctx interface{}, query interface{}) *SearchImproveRequestsService_Search_Call {
	return &SearchImproveRequestsService_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *SearchImproveRequestsService_Search_Call) Run(run func(ctx context.Context, query models.SearchImproveRequestsQuery)) *SearchImproveRequestsService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SearchImproveRequestsQuery))
	})
	return _c
}

func (_c *SearchImproveRequestsService_Search_Call) Return(_a0 []*models.ImproveRequestPreview, _a1 int, _a2 error) *SearchImproveRequestsService_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SearchImproveRequestsService_Search_Call) RunAndReturn(run func(context.Context, models.SearchImproveRequestsQuery) ([]*models.ImproveRequestPreview, int, error)) *SearchImproveRequestsService_Search_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewSearchImproveRequestsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSearchImproveRequestsService creates a new instance of SearchImproveRequestsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSearchImproveRequestsService(t mockConstructorTestingTNewSearchImproveRequestsService) *SearchImproveRequestsService {
	mock := &SearchImproveRequestsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
