// Code generated by mockery v2.20.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/a-novel/forum-service/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// UpdateImproveSuggestionService is an autogenerated mock type for the UpdateImproveSuggestionService type
type UpdateImproveSuggestionService struct {
	mock.Mock
}

type UpdateImproveSuggestionService_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateImproveSuggestionService) EXPECT() *UpdateImproveSuggestionService_Expecter {
	return &UpdateImproveSuggestionService_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx, tokenRaw, suggestion, id, now
func (_m *UpdateImproveSuggestionService) Update(ctx context.Context, tokenRaw string, suggestion *models.ImproveSuggestionForm, id uuid.UUID, now time.Time) (*models.ImproveSuggestion, error) {
	ret := _m.Called(ctx, tokenRaw, suggestion, id, now)

	var r0 *models.ImproveSuggestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.ImproveSuggestionForm, uuid.UUID, time.Time) (*models.ImproveSuggestion, error)); ok {
		return rf(ctx, tokenRaw, suggestion, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.ImproveSuggestionForm, uuid.UUID, time.Time) *models.ImproveSuggestion); ok {
		r0 = rf(ctx, tokenRaw, suggestion, id, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImproveSuggestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.ImproveSuggestionForm, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, tokenRaw, suggestion, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateImproveSuggestionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UpdateImproveSuggestionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRaw string
//   - suggestion *models.ImproveSuggestionForm
//   - id uuid.UUID
//   - now time.Time
func (_e *UpdateImproveSuggestionService_Expecter) Update(ctx interface{}, tokenRaw interface{}, suggestion interface{}, id interface{}, now interface{}) *UpdateImproveSuggestionService_Update_Call {
	return &UpdateImproveSuggestionService_Update_Call{Call: _e.mock.On("Update", ctx, tokenRaw, suggestion, id, now)}
}

func (_c *UpdateImproveSuggestionService_Update_Call) Run(run func(ctx context.Context, tokenRaw string, suggestion *models.ImproveSuggestionForm, id uuid.UUID, now time.Time)) *UpdateImproveSuggestionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.ImproveSuggestionForm), args[3].(uuid.UUID), args[4].(time.Time))
	})
	return _c
}

func (_c *UpdateImproveSuggestionService_Update_Call) Return(_a0 *models.ImproveSuggestion, _a1 error) *UpdateImproveSuggestionService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpdateImproveSuggestionService_Update_Call) RunAndReturn(run func(context.Context, string, *models.ImproveSuggestionForm, uuid.UUID, time.Time) (*models.ImproveSuggestion, error)) *UpdateImproveSuggestionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUpdateImproveSuggestionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateImproveSuggestionService creates a new instance of UpdateImproveSuggestionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateImproveSuggestionService(t mockConstructorTestingTNewUpdateImproveSuggestionService) *UpdateImproveSuggestionService {
	mock := &UpdateImproveSuggestionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
